app:
  build: .
  ports:
    - "5000:5000"
  environment:
    - SERVER_NAME=0.0.0.0:5000
    - DEBUG=False
    - MONGO_URI=mongodb://root:pass@test_mongodb:27017/currencies_db?authSource=admin
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=currencies_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:27017
